#!groovy

// Generated by IBM TransformationAdvisor
// Fri Nov 09 13:25:22 UTC 2018

@Library('MicroserviceBuilder') _
microserviceBuilderPipeline {
    image = 'modresortswar'
    mvnCommands = '--version'
    test='false'
}